version: '3.3'
networks:
  default:
    external:
      name: ${network_name}
services:
  web:
      image: nginx:latest
      container_name: ${proj_name}-nginx
      ports:
          - "80"
      volumes:
          - ./${webroot1}:/${webroot1}
          - ./sitefiles/default.tmpl:/etc/nginx/conf.d/default.tmpl
          - ./scripts:/scripts
      links:
          - php
      environment:
       - nginx_host1=${nginx_host1}
       - nginx_port1=${nginx_port1}
       - proj_name=${proj_name}
       - webroot1=${webroot1}
      command: /scripts/start
#      command: /scripts/dockerize -template /etc/nginx/conf.d/default.tmpl:/etc/nginx/conf.d/default.conf -wait tcp://${proj_name}-phpfpm:9000 /etc/init.d/nginx start
#      command: /scripts/dockerize -template /etc/nginx/conf.d/default.tmpl:/etc/nginx/conf.d/default.conf nginx -g 'daemon off'
#      command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /root/default.conf && /etc/init.d/nginx start" 
  php:
      image: php:7-fpm
      container_name: ${proj_name}-phpfpm
      volumes:
          - .${webroot1}:/${webroot1}
