#!/bin/bash
sleep 4
/scripts/dockerize -template /etc/nginx/conf.d/default.tmpl:/etc/nginx/conf.d/default.conf -wait tcp://${proj_name}-phpfpm:9000 /etc/init.d/nginx start
for (( ; ; ));do
        sleep 50
done
